---
title: Your awesome title
timezone: UTC
collections:
  artists:
    title: Artists
    output: true
  piercers:
    title: Piercers
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: artists
  values:
    main_image: ''
    profile_image: ''
    work_images: 
    layout: profile
- scope:
    path: ''
    type: piercers
  values:
    main_image: ''
    profile_image: ''
    work_images: 
    layout: profile
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: 
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
